# Used by Probot Settings: https://probot.github.io/apps/settings/
repository:
  description: Manage user roles and capabilities.
  labels:
    - name: scope:documentation
      color: 0e8a16
    - name: scope:testing
      color: 5319e7
    - name: good-first-issue
      color: eb6420
    - name: state:unconfirmed
      color: bfe5bf
    - name: state:unsupported
      color: bfe5bf
    - name: command:role-create
      color: c5def5
    - name: command:role-delete
      color: c5def5
    - name: command:role-exists
      color: c5def5
    - name: command:role-list
      color: c5def5
    - name: command:role-reset
      color: c5def5
    - name: command:cap-add
      color: c5def5
    - name: command:cap-list
      color: c5def5
    - name: command:cap-remove
      color: c5def5
